@Host = localhost:8000


### GET users
GET /api/users/
Host: {{Host}}


### Add new user
POST /api/users/
Host: {{Host}}
Content-type: application/json

{
    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "Qwerty123f"
}


### Add another user
POST /api/users/
Host: {{Host}}
Content-type: application/json

{
    "email": "tim@yandex.ru",
    "username": "tim",
    "first_name": "Тимофей",
    "last_name": "Кошечкин",
    "password": "kitting21"
}


### Get user with id=1
GET /api/users/1/
Host: {{Host}}
Content-type: application/json


### Obtain token
POST /api/auth/token/login/
Host: {{Host}}
Content-type: application/json

{
    "password": "Qwerty123f",
    "email": "vpupkin@yandex.ru"
}


### Obtain another token
POST /api/auth/token/login/
Host: {{Host}}
Content-type: application/json

{
    "password": "kitting21",
    "email": "tim@yandex.ru"
}


###
OPTIONS /api/auth/token/login/
Host: {{Host}}
