@Host = localhost:8000
@Token = d5d926ab6f25a42d1aba7efb23e3708f14cdb172


### GET users
GET /api/users/
Host: {{Host}}
Authorization: token {{Token}}

### Add new user
POST /api/users/
Host: {{Host}}
Content-type: application/json

{
    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "Qwerty123f"
}


### Add another user
POST /api/users/
Host: {{Host}}
Content-type: application/json

{
    "email": "tim@yandex.ru",
    "username": "tim",
    "first_name": "Тимофей",
    "last_name": "Кошечкин",
    "password": "kitting21"
}


### Get user with id=1
GET /api/users/1/
Host: {{Host}}
Content-type: application/json
Authorization: token {{Token}}


### Add another user
POST /api/users/
Host: {{Host}}
Content-type: application/json

{
    "email": "ivnpvl@yandex.ru",
    "username": "ivnpvl",
    "first_name": "Иван",
    "last_name": "Павлов",
    "password": "xxbczbczbxa"
}

### Obtain token
POST /api/auth/token/login/
Host: {{Host}}
Content-type: application/json

{
    "password": "xxbczbczbxa",
    "email": "ivnpvl@yandex.ru"
}


### Change password
POST /api/users/set_password/
Host: {{Host}}
Content-type: application/json
Authorization: token {{Token}}

{
    "new_password": "xxbczbczbxa",
    "current_password": "xxbczbczbxa1"
}


### Delete token
POST /api/auth/token/logout/
Host: {{Host}}
Content-type: application/json
Authorization: token {{Token}}


### Current user
GET /api/users/me/
Host: {{Host}}
Content-type: application/json
Authorization: token {{Token}}


### Add subscribtion
POST /api/users/1/subscribe/
Host: {{Host}}
Content-type: application/json
Authorization: token {{Token}}


### Delete subscribtion
DELETE /api/users/1/subscribe/
Host: {{Host}}
Content-type: application/json
Authorization: token {{Token}}